### PR TITLE
Implement collapsible sidebar with smooth animation

### PR DESCRIPTION
**Pull request by ntninja**
The connection indicator was moved to the right so that it always remains
visible everything else is collapsed, when pressing the new menu button.
A few places use slightly different spacing to making everything work.

Unfortunately, Chakra does not provide a “Horizontal Collapsible” component
(only a vertical collapsible and an horizontal overlay drawer), so a DIY approach
inspired by https://v2.chakra-ui.com/community/recipes/horizontal-collapse was
needed by to implement this with nice animations.

Updates to React 18 + Chakra 2 + Framer-Motion 11, since animation support
needs a newer Framer-Motion version which pulls in newer React which again
is only supported by newer Chakra.

Fixes https://github.com/ekzhang/rustpad/issues/61

Based on #75, no real dependency through.

It looks pretty decent :slightly_smiling_face:

### CODE REVIEW

**Comment by ekzhang** [comment]
Sweet! 

> Updates to React 18 + Chakra 2 + Framer-Motion 11

Would you mind actually separating this? I'm very open to having a collapsible sidebar now and so on, but it would be nice to collaborate a bit on it between the two of us and that becomes easier if we split up the dependency stuff 🙏

**Comment by ntninja** [comment]
@ekzhang: Done! (The dependency stuff is entirely constraint to the package*.json files, except for that one commit to initialize the DOM differently.)

**Comment by hanisntsolo** [comment]
Can we take the PR in

**Comment by ekzhang** [comment]
Could you separate the dependency changes into a different PR? I don't really want to review a +1300 line feature PR

**Comment by ntninja** [comment]
@ekzhang: Just in case you’re not aware: You can review the commits individually by just clicking on each in turn and reviewing them that way.

In any case, I've also pushed the first 2 commits over at #83. Thanks for reviewing/merging so far!

**Comment by ekzhang** [comment]
Sorry it's been several months @ntninja — I think we should have the collapsible sidebar, but the interface designer in me isn't happy with the implementation here (specifically the choice of icons, the layout, and so on). I have some time now though so I probably think it'll be quicker to implement from scratch.

**Comment by ntninja** [comment]
Not really sure what you mean, but I guess I’ll see what you mean when its published.

**Pull request closed without merging**
