### PR TITLE
Make RustPad just-enough compatible with EtherPad URLs

### PR DESCRIPTION
**Pull request by ntninja**
Allows RustPad to work as a drop-in alternative for services that have basic EtherPad (popular collaborative document editing tool) integration using an IFrame

Really, it just extracts the two key pieces of information when invoked like:  
https://path/to/rustpad/SomePadName?some=param&userName=AUserName&other=param  
but that is enough to make it useful in the context of the “Collaborative Editing” (=EtherPad) support in the Jitsi Meet video conferencing solution. (SomePadName will be the name of the Jitsi Meet conference and AUserName the name of the currently logged in user.)

Based on https://github.com/ekzhang/rustpad/pull/75, no real dependency through.

### CODE REVIEW

**Comment by ekzhang** [comment]
Interesting, I like the idea! Down to merge this if the CI works.

**Comment by ntninja** [comment]
I just found https://docs.etherpad.org/api/embed_parameters.html which documents the EtherPad parameter list and I found that aside from `userName` and the Pad name there is one more parameter with semantic overlap (`userColor`), so hue is now derived from that if it is set.

There are now also comments about the supported and unsupported parameters that should be helpful and I restructured the code to have all the URL handling in the now renamed `useFromURL.ts` rather than `App.tsx`.

Let me know what you think!

**Comment by ekzhang** [comment]
Sorry it's been a few months @ntninja — I reevaluated my priorities and I don't think I can merge this at this time. Apologies. You might need to fork :(

**Comment by ntninja** [comment]
May I ask why the change in heart?

**Pull request closed without merging**
